apps/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path(
        "",
        views.HomePage.as_view(),
        name="home",
    ),
    path(
        "panel",
        views.Panel.as_view(),
        name="panel",
    ),
]

apps/roles/urls.py
from django.urls import path

from . import views

app_name = "role_app"

urlpatterns = [
    path(
        "roles/",
        views.RoleListView.as_view(),
        name="role_list",
    ),
    path(
        "rol/<pk>/",
        views.RoleDetailView.as_view(),
        name="role_detail",
    ),
    path(
        "add-rol/",
        views.RoleCreateView.as_view(),
        name="role_add",
    ),
    path(
        "success/",
        views.SuccessView.as_view(),
        name="role_success",
    ),
    path(
        "update-rol/<pk>/",
        views.RoleUpdateView.as_view(),
        name="role_update",
    ),
    path(
        "delete-rol/<pk>/",
        views.RoleDeleteView.as_view(),
        name="role_delete",
    ),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        "usuarios/",
        views.UserListView.as_view(),
        name="user_list",
    ),
    path(
        "usuario/<pk>/",
        views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "add-usuario/",
        views.UserCreateView.as_view(),
        name="user_add",
    ),
    path(
        "success/",
        views.SuccessView.as_view(),
        name="user_success",
    ),
    path(
        "update-user/<pk>/",
        views.UserUpdateView.as_view(),
        name="update_user",
    ),
    path(
        "delete-user/<pk>/",
        views.UserDeleteView.as_view(),
        name="delete_user",
    ),
    path(
        "login",
        views.Login.as_view(),
        name="user_login",
    ),
    path(
        "logout",
        views.LogoutView.as_view(),
        name="user_logout",
    ),
    path(
        "update-password",
        views.UpdatePassword.as_view(),
        name="update_password",
    ),
    path(
        "user-verification/<pk>/",
        views.RegisterCodeVerificationView.as_view(),
        name="user_verification",
    ),
]

users_menu/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    re_path("", include("apps.home.urls")),
    re_path("", include("apps.users.urls")),
    re_path("", include("apps.roles.urls")),
]

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = "home/index.html"


class Panel(LoginRequiredMixin, TemplateView):
    template_name = "home/panel.html"
    login_url = reverse_lazy("users_app:user_login")

templates/home/index.html
{% extends 'base.html' %}


{% block title %}
    Home
{% endblock title %}



{% block content %}
    
{% endblock content %}
    

templates/home/panel.html
<section class="section">
    <h1 class="title">Panel de usuario</h1>
    <h2 class="subtitle">Bienvenido: {{user.name}}</h2>
    <aside class="menu">
        <p class="menu-label">Usuarios</p>
        <ul class="menu-list">
          <li><a href="{% url 'users_app:user_list' %}">Listar</a></li>
        </ul>
        <p class="menu-label">Roles</p>
        <ul class="menu-list">
          <li><a href="{% url 'role_app:role_add' %}">Registrar</a></li>
          <li><a href="{% url 'role_app:role_list' %}">Listar</a></li>
        </ul>
      </aside>
</section>

    