apps/roles/urls.py
from django.urls import path

from . import views

app_name = "role_app"

urlpatterns = [
    path(
        "roles/",
        views.RoleListView.as_view(),
        name="role_list",
    ),
    path(
        "rol/<pk>/",
        views.RoleDetailView.as_view(),
        name="role_detail",
    ),
    path(
        "add-rol/",
        views.RoleCreateView.as_view(),
        name="role_add",
    ),
    path(
        "success/",
        views.SuccessView.as_view(),
        name="role_success",
    ),
    path(
        "update-rol/<pk>/",
        views.RoleUpdateView.as_view(),
        name="role_update",
    ),
    path(
        "delete-rol/<pk>/",
        views.RoleDeleteView.as_view(),
        name="role_delete",
    ),
]

users_menu/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    re_path("", include("apps.home.urls")),
    re_path("", include("apps.users.urls")),
    re_path("", include("apps.roles.urls")),
]

apps/roles/models.py
from django.db import models

from apps.abstracts.models import AbstractModel
from apps.menu.models import Menu


class Roles(AbstractModel):
    """
      It is a new model for roles
    Args:
        name ( str ): name of the role
        menu ( str ): menu of the role
    """

    name = models.CharField(max_length=15, null=False)
    menu = models.ManyToManyField(Menu)

    class Meta:
        verbose_name = "Rol"
        verbose_name_plural = "Roles"

    def __str__(self):
        return self.name

apps/roles/forms.py
from django import forms

from .models import Roles


class RoleRegisterForm(forms.ModelForm):
    """Form definition for Roles."""

    class Meta:
        """Meta definition for Rolesform."""

        model = Roles
        fields = (
            "name",
            "menu",
        )

    def clean_name(self):
        if Roles.objects.filter(name=self.cleaned_data["name"]).exists():
            raise forms.ValidationError("El rol ya existe")

        if len(self.cleaned_data["name"]) == 0:
            raise forms.ValidationError("El rol no puede estar vacío")

        return self.cleaned_data["name"]

    def clean_menu(self):
        if len(self.cleaned_data["menu"]) == 0:
            raise forms.ValidationError("El menu no puede estar vacío")

        return self.cleaned_data["menu"]

apps/roles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)
from django.views.generic.edit import FormView

from .forms import RoleRegisterForm
from .models import Roles


class RoleListView(LoginRequiredMixin, ListView):
    model = Roles
    template_name = "roles/roles_list.html"
    context_object_name = "roles_list"

    paginate_by = 10
    ordering = ["-id"]
    queryset = Roles.objects.all()
    login_url = reverse_lazy("users_app:user_login")

    # def get_queryset(self):
    #     role = Roles.objects.get(id=12)
    #     return role.menu.all()


class RoleDetailView(LoginRequiredMixin, DetailView):
    model = Roles
    template_name = "roles/role_detail.html"
    login_url = reverse_lazy("users_app:user_login")


class SuccessView(LoginRequiredMixin, TemplateView):
    template_name = "roles/success.html"
    login_url = reverse_lazy("users_app:user_login")


class RoleCreateView(LoginRequiredMixin, FormView):
    form_class = RoleRegisterForm
    template_name = "roles/add.html"
    success_url = reverse_lazy("role_app:role_success")
    login_url = reverse_lazy("users_app:user_login")

    def form_valid(self, form):
        Roles.objects.create(
            name=form.cleaned_data["name"],
            menu=form.cleaned_data["menu"],
        )
        return super(RoleCreateView, self).form_valid(form)


class RoleUpdateView(LoginRequiredMixin, UpdateView):
    model = Roles
    template_name = "roles/update.html"
    fields = [
        "name",
        "menu",
    ]
    success_url = reverse_lazy("role_app:role_success")
    login_url = reverse_lazy("users_app:user_login")


class RoleDeleteView(LoginRequiredMixin, DeleteView):
    model = Roles
    template_name = "roles/delete.html"
    success_url = reverse_lazy("role_app:role_success")
    login_url = reverse_lazy("users_app:user_login")

templates/roles/add.html
{% extends 'base.html' %}


{% block title %}
    Registrar rol
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Registrar rol</h1>

    <form method="POST">{% csrf_token %}
        {{form.as_p}}
        <button type="submit"></button>
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Agregar</button>
            </div>
          </div>
    </form>
</section>
{% endblock content %}

templates/roles/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar rol
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Eliminar</h1>
    <form method="POST">{% csrf_token %}
        <h2 class="subtitle">Confirme que desea eliminar</h2>
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Confirmar</button>
            </div>
          </div>
    </form>
</section>
    
{% endblock content %}

templates/roles/role_detail.html
{% extends 'base.html' %}


{% block title %}
    Detalle del rol
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Detalle del rol {{roles.name}}</h1>

    <h2 class="subtitle">Toda su información:</h2>
    <p>Id {{roles.id}}</p>
    <p>Menu {{roles.Menu}}</p>
</section>

{% endblock content %}

templates/roles/roles_list.html
{% extends 'base.html' %}


{% block title %}
    Listar usuarios
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Lista de Roles</h1>
    <div class="container is-fluid">
        <div class="notification">
            <div class="fixed-grid has-4-cols">
                {% for roles in roles_list  %}
                <div class="grid">
                  <div class="cell">{{ roles.name }}</div>
                  <div class="cell"><a href="{% url 'role_app:role_detail' roles.id %}">Ver</a></div>
                  <div class="cell"><a href="{% url 'role_app:role_update' roles.id %}">Modificar</a></div>
                  <div class="cell"><a href="{% url 'role_app:role_delete' roles.id %}">Eliminar</a></div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="container is-fluid">
        
        {% if is_paginated  %}
        <nav class="pagination" role="navigation" aria-label="pagination">
            
            {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}" class="pagination-previous">Atras</a>    
            {% endif %}
                
            {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}" class="pagination-next">Siguiente</a>
            {% endif %}

            <nav class="pagination-list">
              
              {% for pagina in paginator.page_range  %}
              <li>
                <a href="?page={{pagina}}" class="pagination-link" aria-label="Siguiente pagina">{{pagina}}</a>
              </li>
              {% endfor %}
                
              
            </nav>
        </nav>    
        {% endif %}
    </div>
</section>
{% endblock content %}

templates/roles/success.html
{% extends 'base.html' %}


{% block title %}
    Operación exitosa
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Operación satisfactoria en el rol</h1>
</section>
{% endblock content %}

templates/roles/update.html
{% extends 'base.html' %}


{% block title %}
    Modifica rol
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Modificar datos del Rol</h1>
    <form method="POST">{% csrf_token %}
        {{form.as_p}}
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Modificar</button>
            </div>
          </div>
    </form>
</section>
{% endblock content %}