apps/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        "usuarios/",
        views.UserListView.as_view(),
        name="user_list",
    ),
    path(
        "usuario/<pk>/",
        views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "add-usuario/",
        views.UserCreateView.as_view(),
        name="user_add",
    ),
    path(
        "success/",
        views.SuccessView.as_view(),
        name="user_success",
    ),
    path(
        "update-user/<pk>/",
        views.UserUpdateView.as_view(),
        name="update_user",
    ),
    path(
        "delete-user/<pk>/",
        views.UserDeleteView.as_view(),
        name="delete_user",
    ),
    path(
        "login",
        views.Login.as_view(),
        name="user_login",
    ),
    path(
        "logout",
        views.LogoutView.as_view(),
        name="user_logout",
    ),
    path(
        "update-password",
        views.UpdatePassword.as_view(),
        name="update_password",
    ),
    path(
        "user-verification/<pk>/",
        views.RegisterCodeVerificationView.as_view(),
        name="user_verification",
    ),
]

users_menu/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    re_path("", include("apps.home.urls")),
    re_path("", include("apps.users.urls")),
    re_path("", include("apps.roles.urls")),
]

apps/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from apps.abstracts.models import AbstractModel
from apps.roles.models import Roles

from .managers import UserManager


class User(PermissionsMixin, AbstractBaseUser, AbstractModel):
    """
      It is a new model for custom user
    Args:
        username ( str ): knick name.
        email ( str ): email of the user
        rol ( str ): role of the user
        is_staff ( bool ): is an user with permissions of the admin panel?
        name ( str ): name of the user
        last_name ( str ): last name of the user
        age ( int ): age of the user
        phone ( str ): phone number of the user
        address ( str ): address of the user

    """

    username = models.CharField(max_length=10, null=False, unique=True)
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(default=False)
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    age = models.IntegerField(null=True, blank=True)
    phone = models.CharField(max_length=10, null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)
    role = models.ForeignKey(Roles, on_delete=models.CASCADE, null=True, blank=True)
    register_code = models.CharField(max_length=6, blank=True)
    is_active = models.BooleanField(default=False)
    session_duration = models.IntegerField(default=3600)

    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["email"]
    objects = UserManager()

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate

from .models import User


class UserRegisterForm(forms.ModelForm):
    """Form definition for User."""

    password1 = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Contraseña"},
        ),
    )
    password2 = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Repetir Contraseña"},
        ),
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            "username",
            "name",
            "last_name",
            "email",
            "age",
            "phone",
            "address",
            "role",
        )

    def clean_password2(self):
        if self.cleaned_data["password1"] != self.cleaned_data["password2"]:
            self.add_error("password2", "Las contraseñas no son iguales")

    def clean_password1(self):
        if len(self.cleaned_data["password1"]) < 8:
            # self.add_error("password1", "La contraseña debe tener al menos 8 caracteres")
            raise forms.ValidationError(
                "La contraseña debe tener al menos 8 caracteres",
            )
        return self.cleaned_data["password1"]

    def clean_username(self):
        if User.objects.filter(username=self.cleaned_data["username"]).exists():
            raise forms.ValidationError("El usuario ya existe")

        if len(self.cleaned_data["username"]) == 0:
            raise forms.ValidationError("El usuario no puede estar vacío")

        return self.cleaned_data["username"]

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data["email"]).exists():
            raise forms.ValidationError("El email ya existe")

        if len(self.cleaned_data["email"]) == 0:
            raise forms.ValidationError("El email no puede estar vacío")

        return self.cleaned_data["email"]


class LoginForm(forms.Form):
    username = forms.CharField(
        label="username",
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "username",
                "style": "{margin: 10px}",
            },
        ),
    )
    password = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Contraseña"},
        ),
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]

        if not authenticate(username=username, password=password):
            raise forms.ValidationError("Los datos del usuario no son correctos")

        return cleaned_data


class UpdatePasswordForm(forms.Form):
    password1 = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Contraseña actual"},
        ),
    )
    password2 = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Contraseña nueva"},
        ),
    )

    def clean_password2(self):
        if len(self.cleaned_data["password2"]) < 8:
            # self.add_error("password1", "La contraseña debe tener al menos 8 caracteres")
            raise forms.ValidationError(
                "La contraseña debe tener al menos 8 caracteres",
            )
        return self.cleaned_data["password2"]


class VerificationForm(forms.Form):
    register_code = forms.CharField(required=True, max_length=6)

    def __init__(self, pk, *args, **kwargs):
        self.user_id = pk
        return super(VerificationForm, self).__init__(*args, **kwargs)

    def clean_register_code(self):
        obtained_code = self.cleaned_data["register_code"]
        if len(obtained_code) == 6:
            # Verficate if the obtained code and the user id are valids
            active = User.objects.validation_of_code(
                self.user_id,
                obtained_code,
            )
            if not active:
                raise forms.ValidationError("El código es incorrecto")
        else:
            raise forms.ValidationError("El código es incorrecto")

apps/users/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)
from django.views.generic.edit import FormView

from .forms import LoginForm, UpdatePasswordForm, UserRegisterForm, VerificationForm
from .functions import code_generator
from .models import User


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "users/users_list.html"
    context_object_name = "users_list"

    paginate_by = 10
    ordering = ["-id"]
    queryset = User.objects.all()
    login_url = reverse_lazy("users_app:user_login")


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "users/user_detail.html"
    login_url = reverse_lazy("users_app:user_login")


class SuccessView(TemplateView):
    template_name = "users/success.html"


class UserCreateView(FormView):
    template_name = "users/add.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("users_app:user_success")

    def form_valid(self, form):
        # generate the random code
        random_code = code_generator()

        user = User.objects.create_user(
            form.cleaned_data["username"],
            form.cleaned_data["email"],
            form.cleaned_data["password1"],
            name=form.cleaned_data["name"],
            last_name=form.cleaned_data["last_name"],
            age=form.cleaned_data["age"],
            phone=form.cleaned_data["phone"],
            address=form.cleaned_data["address"],
            role=form.cleaned_data["role"],
            register_code=random_code,
        )
        # Send the register_code to user's email address
        # send_mail(
        #     "Bienvenido al sistema",
        #     f"Bienvenido al sistema, tu codigo de registro es: {random_code}",
        #     "
        subject = "Confrimación de email"
        message = f"Código de verificación: {random_code}"
        sender_email = settings.EMAIL_HOST_USER
        send_mail(
            subject,
            message,
            sender_email,
            [
                form.cleaned_data["email"],
            ],
        )
        # rederigite to validation page

        return HttpResponseRedirect(
            reverse(
                "users_app:user_verification",
                kwargs={
                    "pk": user.id,
                },
            ),
        )


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = "users/update.html"
    fields = [
        "username",
        "name",
        "last_name",
        "email",
        "age",
        "phone",
        "address",
        "role",
    ]
    success_url = reverse_lazy("users_app:user_success")
    login_url = reverse_lazy("users_app:user_login")


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = "users/delete.html"
    success_url = reverse_lazy("users_app:user_success")
    login_url = reverse_lazy("users_app:user_login")


class Login(FormView):
    template_name = "users/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("home_app:home")

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password"],
        )
        if user is not None:
            login(self.request, user)
        return super(Login, self).form_valid(form)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse("home_app:home"),
        )


class UpdatePassword(LoginRequiredMixin, FormView):
    template_name = "users/update_password.html"
    form_class = UpdatePasswordForm
    login_url = reverse_lazy("users_app:user_login")

    def form_valid(self, form):
        current_user = self.request.user
        user = authenticate(
            username=current_user.username,
            password=form.cleaned_data["password1"],
        )
        if user:
            new_password = form.cleaned_data["password2"]
            current_user.set_password(new_password)
            current_user.save()

        logout(self.request)
        return super(UpdatePassword, self).form_valid(form)


class RegisterCodeVerificationView(FormView):
    template_name = "users/verification.html"
    form_class = VerificationForm
    success_url = reverse_lazy("users_app:user_login")

    def get_form_kwargs(self):
        kwargs = super(RegisterCodeVerificationView, self).get_form_kwargs()
        kwargs.update(
            {
                "pk": self.kwargs["pk"],
            }
        )
        return kwargs

    def form_valid(self, form):
        User.objects.filter(id=self.kwargs["pk"]).update(is_active=True)
        return super(RegisterCodeVerificationView, self).form_valid(form)

templates/users/add.html
{% extends 'base.html' %}


{% block title %}
    Registrar usuario
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Registrar usuario</h1>
    <form method="POST">{% csrf_token %}
        {{form.as_p}}
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Registrar</button>
            </div>
          </div>
    </form>
</section>

{% endblock content %}

templates/users/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar usuario
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Eliminar</h1>
    <form method="POST">{% csrf_token %}
        <h2 class="subtitle">Confirme que desea eliminar</h2>
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Confirmar</button>
            </div>
          </div>
    </form>
</section>

{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}


{% block title %}
    Login
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Acceder al sistema</h1>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Acceder</button>
            </div>
          </div>
    </form>
  </section>

{% endblock content %}

templates/users/success.html
{% extends 'base.html' %}


{% block title %}
    Operación exitosa
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Operación satisfactoria en el usuario</h1>
</section>    
{% endblock content %}

templates/users/update.html
{% extends 'base.html' %}


{% block title %}
    Login
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Modificar datos del Usuario</h1>
    <form method="POST">{% csrf_token %}
        {{form.as_p}}
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Modificar</button>
            </div>
          </div>
    </form>
</section>
    
{% endblock content %}

templates/users/update_password.html
{% extends 'base.html' %}


{% block title %}
    Actualizar contraseña
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Cambiar contraseña: {{user.name}}</h1>
    <form method="POST">{% csrf_token %}
        {{form.as_p}}
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Cambiar</button>
            </div>
          </div>
    </form>
</section>
{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %}


{% block title %}
    Detalle del usuario
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Detalle del usuario {{user.username}}</h1>

    <h2 class="subitle">Toda su información:</h2>

    <p>Id {{user.id}}</p>
    <p>Email: {{user.email}}</p>
    <p>Nombre: {{user.name}}</p>
    <p>Apellidos: {{user.last_name}}</p>
    <p>Edad: {{user.age}}</p>
    <p>Teléfono: {{user.phone}}</p>
    <p>Dirección: {{user.address}}</p>
    <p>Rol: {{user.role}}</p>
</section>
{% endblock content %}

templates/users/users_list.html
{% extends 'base.html' %}


{% block title %}
    Listar usuarios
{% endblock title %}
{% block content %}
<section class="section">
  <h1 class="title">Lista de usuarios</h1>
  <div class="container is-fluid">
      <div class="notification">
          <div class="fixed-grid has-7-cols">
              {% for user in users_list  %}
              <div class="grid">
                <div class="cell">{{ user.name }}</div>
                <div class="cell">{{user.last_name}}</div>
                <div class="cell">{{user.age}}</div>
                <div class="cell">{{user.role}}</div>
                <div class="cell"><a href="{% url 'users_app:user_detail' user.id %}">Ver</a></div>
                <div class="cell"><a href="{% url 'users_app:update_user' user.id %}">Modificar</a></div>
                <div class="cell"><a href="{% url 'users_app:delete_user' user.id %}">Eliminar</a></div>
              </div>
              {% endfor %}
          </div>
      </div>
  </div>
  <div class="container is-fluid">
        
    {% if is_paginated  %}
    <nav class="pagination" role="navigation" aria-label="pagination">
        
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}" class="pagination-previous">Atras</a>    
        {% endif %}
            
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}" class="pagination-next">Siguiente</a>
        {% endif %}

        <nav class="pagination-list">
          
          {% for pagina in paginator.page_range  %}
          <li>
            <a href="?page={{pagina}}" class="pagination-link" aria-label="Siguiente pagina">{{pagina}}</a>
          </li>
          {% endfor %}
            
          
        </nav>
    </nav>    
    {% endif %}
</div>
</section>

    
{% endblock content %}

templates/users/verification.html
{% extends 'base.html' %}


{% block title %}
    Verificar código
{% endblock title %}
{% block content %}
<section class="section">
    <h1 class="title">Verificación de email</h1>
    <h2 class="subtitle">Ingrese el código de Verificación</h2>
    <form method="POST">{% csrf_token %}
        {{form.as_p}}
        <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Confirmar</button>
            </div>
          </div>
    </form>
</section>
    
{% endblock content %}